<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/12/14 14:34:45

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=GL-Events-tests',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
