<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/12/14 14:34:45
sfConfig::add(array(
  'app_ad_options' => array (
  'account_suffix' => '@testathon.net',
  'base_dn' => 'DC=testathon,DC=net',
  'domain_controllers' => 
  array (
    0 => 'testathon.net',
  ),
  'ad_username' => 'stuart',
  'ad_password' => 'stuart',
  'recursive_groups' => false,
),
  'app_ad_ntlm_active' => false,
  'app_ad_kerberos_active' => false,
  'app_ad_group_authorize' => 'GROUP',
  'app_ad_master_ou' => 'OU=users',
  'app_ad_secure_group_name' => false,
  'app_ad_group_not_allowed' => false,
));
